# Generated by Django 2.0.3 on 2018-04-24 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_auto_20180423_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['pinned', '-last_activity']},
        ),
    ]
