# Generated by Django 2.0.3 on 2018-04-24 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0003_auto_20180424_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-pinned', '-last_activity']},
        ),
    ]
