# Generated by Django 2.0.3 on 2018-04-27 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0004_auto_20180424_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
