# Generated by Django 2.0.3 on 2018-04-30 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0005_auto_20180427_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='thread',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
