# Generated by Django 2.0.3 on 2018-04-30 16:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0006_auto_20180430_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 30, 16, 17, 11, 129557, tzinfo=utc)),
        ),
    ]
