# Generated by Django 2.0.3 on 2018-04-30 16:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0007_auto_20180430_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
